import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "../components/ui/Navbar";
import Sidebar from "../components/ui/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
      <body className="flex flex-col h-screen bg-gray-100">
        <Navbar />

        <div className="flex ">
          <Sidebar />
           <main className="flex flex-col w-full">
            {children}
          </main>
          
         
        </div>
        

         
        

      </body>
    </html>
  );
}
